# Generated by Django 5.2.6 on 2025-09-08 17:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'category',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'db_table': 'organization',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='organizatio_name_bcc2ee_idx')],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline')], default='ONLINE', max_length=10)),
                ('name', models.CharField(max_length=120)),
                ('model', models.CharField(blank=True, max_length=120, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=120, null=True)),
                ('installed_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='dispositivos.category')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='dispositivos.organization')),
            ],
            options={
                'db_table': 'device',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='dispositivos.organization'),
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('severity', models.CharField(choices=[('GRAVE', 'Grave'), ('ALTO', 'Alto'), ('MEDIANO', 'Mediano')], max_length=10)),
                ('message', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='dispositivos.device')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='dispositivos.organization')),
            ],
            options={
                'db_table': 'alert',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='dispositivos.organization')),
            ],
            options={
                'db_table': 'zone',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='device',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='dispositivos.zone'),
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('value', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('unit', models.CharField(max_length=20)),
                ('measured_at', models.DateTimeField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='dispositivos.device')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='dispositivos.organization')),
            ],
            options={
                'db_table': 'measurement',
                'ordering': ['-measured_at'],
                'indexes': [models.Index(fields=['device'], name='measurement_device__7538e2_idx'), models.Index(fields=['organization'], name='measurement_organiz_39ffcb_idx'), models.Index(fields=['-measured_at'], name='measurement_measure_f3f822_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('value__gte', 0)), name='measurement_value_gte_0')],
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['organization', 'name'], name='category_organiz_4c008a_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['organization'], name='category_organiz_ade38f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('organization', 'name')},
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['organization'], name='alert_organiz_be90dd_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['device'], name='alert_device__f31839_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['severity'], name='alert_severit_877930_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['is_resolved'], name='alert_is_reso_bfbffa_idx'),
        ),
        migrations.AddIndex(
            model_name='zone',
            index=models.Index(fields=['organization', 'name'], name='zone_organiz_a2adb8_idx'),
        ),
        migrations.AddIndex(
            model_name='zone',
            index=models.Index(fields=['organization'], name='zone_organiz_27e408_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='zone',
            unique_together={('organization', 'name')},
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['organization'], name='device_organiz_dfeb88_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['category'], name='device_categor_020454_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['zone'], name='device_zone_id_b296ed_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='device',
            unique_together={('organization', 'name')},
        ),
    ]
