# Generated by Django 5.2.6 on 2025-09-12 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAlertEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'product_alert_event',
            },
        ),
        migrations.AlterModelOptions(
            name='alert',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='measurement',
            name='measurement_value_gte_0',
        ),
        migrations.RemoveIndex(
            model_name='alert',
            name='alert_severit_877930_idx',
        ),
        migrations.RemoveIndex(
            model_name='alert',
            name='alert_is_reso_bfbffa_idx',
        ),
        migrations.RemoveIndex(
            model_name='productalert',
            name='product_ale_product_42a12e_idx',
        ),
        migrations.RemoveIndex(
            model_name='productalert',
            name='product_ale_alert_i_132ada_idx',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='alert',
        ),
        migrations.RemoveField(
            model_name='product',
            name='alerts',
        ),
        migrations.AddField(
            model_name='productalertevent',
            name='measurement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_events', to='dispositivos.measurement'),
        ),
        migrations.AddField(
            model_name='productalertevent',
            name='product_alert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='dispositivos.productalert'),
        ),
    ]
