# Generated by Django 5.2.6 on 2025-09-12 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0002_productalertevent_alter_alert_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='is_resolved',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='resolved_at',
        ),
        migrations.AlterField(
            model_name='alert',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
